apiVersion: v1
kind: Service
metadata:
  name: firefly-iii-importer
  labels:
    app: firefly-iii-importer
spec:
  clusterIP: None
  ports:
    - port: 8080
  selector:
    app: firefly-iii-importer
    tier: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii-importer
  labels:
    app: firefly-iii-importer
spec:
  selector:
    matchLabels:
      app: firefly-iii-importer
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: firefly-iii-importer
        tier: frontend
    spec:
      containers:
      - image: fireflyiii/data-importer:version-1.7.8
        name: firefly-iii-importer
        env:
        - name: FIREFLY_III_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: firefly-iii-secrets
              key: access_token
        - name: FIREFLY_III_URL
          value: "http://firefly-iii:8080"
        - name: TRUSTED_PROXIES
          value: "**"
        ports:
        - containerPort: 8080
          name: firefly-iii
        imagePullPolicy: Always
