blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/firefly-iii/firefly-iii/discussions
    about: Please ask and answer questions here.
  - name: I need support! 
    url: https://github.com/firefly-iii/firefly-iii/discussions
    about: I think I broke something...
