{{- if and (.Values.backup.enabled) (eq .Values.backup.destination "pvc") (eq .Values.backup.pvc.existingClaim "") }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "firefly-db.fullname" . }}-backup-job
  labels:
    app: {{ template "firefly-db.name" . }}
    chart: {{ template "firefly-db.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-delete,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 100
  parallelism: 1
  completions: 1
  template:
    {{- include "backupJobSpec" . | indent 4 }}
{{- end }}
