{{- if not .Values.configs.existingSecret }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "firefly-db.fullname" . }}-config
  labels:
    app: {{ template "firefly-db.name" . }}
    chart: {{ template "firefly-db.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.configs }}
  {{- if ne $key "DBHOST" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  DBHOST: {{ (default (include "firefly-db.fullname" .) .Values.configs.DBHOST) | quote }}
{{- end }}
