apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firefly-iii.fullname" . }}
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config.env }}
  {{- if ne $key "DB_HOST" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  DB_HOST: {{ (default (printf "%s-firefly-db" .Release.Name) .Values.config.env.DB_HOST) | quote }}
